name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'oracle'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.3
      - name: Build app
        run: make build
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
          - name: Code coverage
            uses: paambaati/codeclimate-action@v5.0.0g
            env:
              CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
              JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
            with:
              coverageCommand: make report
              coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
              token: ${{ secrets.GITHUB_TOKEN }}
              min-coverage-overall: 40
              min-coverage-changed-files: 60