name: Java CI

on:
  - push
  - pull_request


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'oracle'
      - name: Build app
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.3
          arguments: build
#          build-root-directory: app
      - name: Build with Gradle
        working-directory: app
        run: ./gradlew build
      - name: Code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          workingDirectory: app
          coverageCommand: make report
          coverageLocations: build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60
