name: Java CI

on:
  - push
  - pull_request


jobs:

  build:
    runs-on: ubuntu-latest

    env:
      APP_DIR: ${{github.workspace}}/app/

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'oracle'
      - name: Build app
        run:
            cd APP_DIR
            make build
#        uses: gradle/gradle-build-action@v3
#        with:
#          gradle-version: 8.3
#          arguments: build
#          build-root-directory: app
      - name: Code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/app/src/main/java"
        with:
          build-root-directory: app
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
